### ISSUE TITLE
v3到底怎么用啊？没搞懂

### ISSUE THREAD

**Issue by AP0rPi7uQ9** [stack-labs/questions#87]
不用Micro。只想用etcd的话，

Go Micro v3 应该怎么写啊？官网也没个etcd的案例，好难。。

**Comment by youyouni** [comment]
V3走的商业平台化，还是散了吧。感觉micro凉了

**Comment by AP0rPi7uQ9** [comment]
啊朋友再见啊朋友再见啊朋友再见吧再见吧再见吧
